### PR TITLE
Migrations for Organization Clearance Feature

### PR DESCRIPTION
**Pull request by rashm1n**
## Purpose
Migration scripts for organization addition

## Related Issues
* wso2-enterprise/choreo#6263
* wso2-enterprise/choreo#7598

### CODE REVIEW

**Comment by CrowleyRajapakse** [comment]
If possible please check and update other "Organization" used tables as well, Ex: AM_KEY_MANAGER related changes, following kind of errors get thrown if we start a current migrated pack for related to this table mostly,

`Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'ORGANIZATION' in 'where clause'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.27.jar:8.0.27]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.27.jar:8.0.27]`

**Comment by HiranyaKavishani** [comment]
Following alter queries have to be included in to 410 Migration Doc

```
create index IDX_AAI_ORG on AM_API (ORGANIZATION);
ALTER TABLE AM_API_DEFAULT_VERSION  ADD COLUMN ORGANIZATION VARCHAR(100) NULL;
ALTER TABLE AM_API_REVISION_METADATA MODIFY COLUMN REVISION_UUID VARCHAR(255);

ALTER TABLE AM_GW_API_DEPLOYMENTS DROP FOREIGN KEY AM_GW_API_DEPLOYMENTS_ibfk_1 ;
ALTER TABLE AM_GW_API_DEPLOYMENTS ADD CONSTRAINT AM_GW_API_DEPLOYMENTS_ibfk_1 FOREIGN KEY (API_ID) REFERENCES AM_GW_PUBLISHED_API_DETAILS(API_ID) ON UPDATE CASCADE ON DELETE CASCADE;


ALTER TABLE AM_GW_API_ARTIFACTS DROP FOREIGN KEY AM_GW_API_ARTIFACTS_ibfk_1;
ALTER TABLE AM_GW_API_ARTIFACTS ADD CONSTRAINT AM_GW_API_ARTIFACTS_ibfk_1 FOREIGN KEY (API_ID) REFERENCES AM_GW_PUBLISHED_API_DETAILS(API_ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE AM_API_RATINGS DROP FOREIGN KEY AM_API_RATINGS_ibfk_1;
ALTER TABLE AM_API_RATINGS ADD CONSTRAINT AM_API_RATINGS_ibfk_1 FOREIGN KEY(API_ID) REFERENCES AM_API(API_ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE AM_API_COMMENTS DROP FOREIGN KEY AM_API_COMMENTS_ibfk_1;
ALTER TABLE AM_API_COMMENTS ADD CONSTRAINT AM_API_COMMENTS_ibfk_1 FOREIGN KEY(API_ID) REFERENCES AM_API(API_ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE AM_API_LC_EVENT DROP FOREIGN KEY AM_API_LC_EVENT_ibfk_1;
ALTER TABLE AM_API_LC_EVENT ADD CONSTRAINT AM_API_LC_EVENT_ibfk_1 FOREIGN KEY(API_ID) REFERENCES AM_API(API_ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE AM_SUBSCRIPTION DROP FOREIGN KEY AM_SUBSCRIPTION_ibfk_2;
ALTER TABLE AM_SUBSCRIPTION ADD CONSTRAINT AM_SUBSCRIPTION_ibfk_2 FOREIGN KEY(API_ID) REFERENCES AM_API(API_ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE AM_SECURITY_AUDIT_UUID_MAPPING DROP FOREIGN KEY AM_SECURITY_AUDIT_UUID_MAPPING_ibfk_1;
ALTER TABLE AM_SECURITY_AUDIT_UUID_MAPPING ADD CONSTRAINT AM_SECURITY_AUDIT_UUID_MAPPING_ibfk_1 FOREIGN KEY (API_ID) REFERENCES AM_API(API_ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE AM_API_REVISION_METADATA ADD FOREIGN KEY(REVISION_UUID) REFERENCES AM_REVISION(REVISION_UUID) ON DELETE CASCADE;

ALTER TABLE AM_REVISION ADD FOREIGN KEY (API_UUID) REFERENCES AM_API(API_UUID) ON DELETE CASCADE;

ALTER TABLE AM_APPLICATION_REGISTRATION DROP FOREIGN KEY AM_APPLICATION_REGISTRATION_ibfk_2 ;
ALTER TABLE AM_APPLICATION_REGISTRATION ADD CONSTRAINT AM_APPLICATION_REGISTRATION_ibfk_2 FOREIGN KEY (APP_ID) REFERENCES AM_APPLICATION(APPLICATION_ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE AM_APPLICATION_KEY_MAPPING DROP FOREIGN KEY AM_APPLICATION_KEY_MAPPING_ibfk_1 ;
ALTER TABLE AM_APPLICATION_KEY_MAPPING ADD CONSTRAINT AM_APPLICATION_KEY_MAPPING_ibfk_1 FOREIGN KEY (APPLICATION_ID) REFERENCES AM_APPLICATION(APPLICATION_ID) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE AM_SUBSCRIPTION DROP FOREIGN KEY AM_SUBSCRIPTION_ibfk_1 ;
ALTER TABLE AM_SUBSCRIPTION ADD CONSTRAINT AM_SUBSCRIPTION_ibfk_1 FOREIGN KEY (APPLICATION_ID) REFERENCES AM_APPLICATION(APPLICATION_ID) ON UPDATE CASCADE ON DELETE CASCADE;
```

**Comment by HiranyaKavishani** [comment]
@CrowleyRajapakse , I think the above issue (AM_KEY_MANAGER) is relevant to doc issue [1]
[1] https://github.com/wso2/docs-apim/issues/4163

**Comment by HiranyaKavishani** [comment]
Close the issue as it is already added

**Pull request closed without merging**
